config/routes.rb
Rails.application.routes.draw do
  get 'latest/:station_number' => 'publicvars#latest'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'dashboards' => 'dashboards#index', as: :dashboards
  get  'dashboards/latest_chart_data' => 'dashboards#latest_chart_data'
  get  'dashboards/latest/:component' => 'dashboards#latest_chart_channel_component_data', as: :latest_chart_component_data
  get 'aqmesh_data/grab' => 'aqmesh_data#grab'
  get 'aqmesh_data/latest_timestamp/:n' => 'aqmesh_data#latest_timestamp'
  get 'aqmesh_channels/latest/:n/:label' => 'aqmesh_channels#latest_final'
  resources :aqmesh_channels
  resources :aqmesh_data
  get 'units/grab' => 'units#grab'
  get 'sensors/grab' => 'sensors#grab'
  resources :stations
  resources :servers
  resources :units
  resources :sensors

end

app/models/aqmesh_channel.rb
class AqmeshChannel < ActiveRecord::Base
  belongs_to :aqmesh_datum

  def self.latest_final_by_label(n,label)
    where("label = ?",label.upcase).last(n).map(&:final)  
  end

  def self.to_csv(col_sep)
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/aqmesh_datum.rb
class AqmeshDatum < ActiveRecord::Base
  has_many :aqmesh_channels
  belongs_to :station
  validates :timestamp, uniqueness: true

  def self.latest_timestamp(n) 
    last(n).map(&:timestamp)
  end
  
  def self.to_csv(col_sep)
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/grab.rb
require 'open-uri'
class Grab
  
  def initialize
    uri    = "http://api.envirologger.net/2.0/interface/"
    apikey = "a7ea099c-E/7e9f-6a94-Qnu4-FtFD-BRPE-2srr-fc09-aae3/"
    @api   = uri.concat(apikey)
  end

  def getapi(q)
    fullapi = @api.concat(q)
    content = open(fullapi).read
    JSON.parse(content)
  end

  def aqmeshdata_to_db(g,id)

    g.each do |e|
      aqmdata = AqmeshDatum.new
      aqmdata.timestamp = e["Timestamp"]
      aqmdata.display_type = e["DisplayType"]
      aqmdata.battery = e["Battery"]
      aqmdata.particle_protocol = e["ParticleProtocol"]
      aqmdata.gas_protocol = e["GasProtocol"]
      aqmdata.P1 = e["P1"]
      aqmdata.P2 = e["P2"]
      aqmdata.P3 = e["P3"]
      aqmdata.T1 = e["T1"]
      aqmdata.T2 = e["T2"]
      aqmdata.T3 = e["T3"]
      aqmdata.station_id = id

      if aqmdata.save 

        e["Channels"].each do |f| 
          pre_scaled = f["PreScaled"]
          scaled     = f["Scaled"]
          final      = f["Final"]
          offset     = f["Offset"]
          slope      = f["Slope"]
          status     = f["Status"]
          unit       = f["Unit"]
          sensor     = f["Sensor"]
          label      = f["Label"]
          
          AqmeshChannel.create!(aqmesh_datum_id: aqmdata.id,pre_scaled: pre_scaled, scaled: scaled, final: final, offset: offset, slope: slope, status: status, unit: unit, sensor: sensor, label: label.strip) 
        end

        p "========================= saved #{e['Timestamp']} ==========================="

      else 
        p "xxxxxxxxxxxxxxxxxxxxxxxxxx skipped #{e['Timestamp']} xxxxxxxxxxxxxxxxxxxxxxxx" 
      end

    end

  end

end

app/models/prepare_data_chart.rb
class PrepareDataChart
  def latest(n,label)
    result    = []
    timestamp = AqmeshDatum.latest_timestamp(n)
    label.each do |x|
      pradata   = {}
      pradata[:name] = x
      val            = AqmeshChannel.latest_final_by_label(n,x)
      pradata[:data] = arrays_to_hash(timestamp,val)
      result << pradata
    end
    result
  end

  def arrays_to_hash(keys,values)
    Hash[keys.zip(values)]
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  has_many :role_groups
end

app/models/role_group.rb
class RoleGroup < ActiveRecord::Base
  belongs_to :role
  belongs_to :station
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  validates :name, uniqueness: true
end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :stations
  validates :name, uniqueness: true
  validates :number, uniqueness: true
end

app/models/station.rb
class Station < ActiveRecord::Base
  self.inheritance_column = "inheritance_type"
  belongs_to :server
  has_many :aqmesh_data
  has_many :role_groups
  validates :name, uniqueness: true
  validates :number, uniqueness: true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aqmesh_data_helper.rb
module AqmeshDataHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def set_min_max_from(highest_num,count_part,part)
    comp   = {}
    p         = highest_num / count_part
    comp['min'] = p * (part-1) 
    comp['max'] = p * part 
    comp
  end

  def set_indicator_for(*args)
    label,value = *args

    if label.upcase == 'O3'
      indicator_color(value,51,101,169,209,748)
    elsif label.upcase == 'SO2'
      indicator_color(value,41,81,381,801,1600)
    elsif label.upcase == 'CO' 
      indicator_color(value,1.1,2.1,10,17,34)
    elsif label.upcase == 'NO2' 
      indicator_color(value,41,81,181,281,400)
    end
  end

  def indicator_color(*args)
    value,kpi1,kpi2,kpi3,kpi4,kpi5 = args
    bad_to_good_color = ['black','purple','red','yellow','green','blue']

    case value
    when 0..(kpi1.to_i-1) then result = bad_to_good_color[5]
    when kpi1..(kpi2.to_i-1) then result = bad_to_good_color[4]
    when kpi2..(kpi3.to_i-1) then result = bad_to_good_color[3]
    when kpi3..(kpi4.to_i-1) then result = bad_to_good_color[2]
    when kpi4..(kpi5.to_i-1) then result = bad_to_good_color[1] 
    else 
      result = bad_to_good_color[0]
    end
    result
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publicvars_helper.rb
module PublicvarsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Envirologer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"> 

    <%= javascript_include_tag 'plugins/jQuery/jquery-2.2.3.min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%#= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>-->
    
    
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyAiEHbXZRHEh73adWbHCZN_btwrXHdW7UQ", :cache => true %>
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCJQx1BmYiSORsZl5bCTpSXAjSESF1yfl8&callback=initMap" type="text/javascript"></script>-->
    <%# javascript_include_tag 'gmap3.min', :cache => true %>  
  </head>
  <!-- ADD THE CLASS sidedar-collapse TO HIDE THE SIDEBAR PRIOR TO LOADING THE SITE -->
  <body class="hold-transition skin-blue sidebar-collapse sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="../../index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>E</b>L</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Enviro</b>Logger</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= render "shared/navbar_custom_menu" %>
        </nav>
      </header>

      <%= render "shared/sidebar" %>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <%= render "shared/breadcrumb" %>

        <!-- Main Content -->
        <section class="content">
          <%= yield %>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.5
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
        reserved.
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript:void(0)">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript:void(0)">
                  <i class="menu-icon fa fa-user bg-yellow"></i>

                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                    <p>New phone +1(800)555-1234</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript:void(0)">
                  <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                    <p>nora@example.com</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript:void(0)">
                  <i class="menu-icon fa fa-file-code-o bg-green"></i>

                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                    <p>Execution time 5 seconds</p>
                  </div>
                </a>
              </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript:void(0)">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>

                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript:void(0)">
                  <h4 class="control-sidebar-subheading">
                    Update Resume
                    <span class="label label-success pull-right">95%</span>
                  </h4>

                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript:void(0)">
                  <h4 class="control-sidebar-subheading">
                    Laravel Integration
                    <span class="label label-warning pull-right">50%</span>
                  </h4>

                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript:void(0)">
                  <h4 class="control-sidebar-subheading">
                    Back End Framework
                    <span class="label label-primary pull-right">68%</span>
                  </h4>

                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                  </div>
                </a>
              </li>
            </ul>
            <!-- /.control-sidebar-menu -->

          </div>
          <!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
          <!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked>
                </label>

                <p>
                Some information about this general settings option
                </p>
              </div>
              <!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Allow mail redirect
                  <input type="checkbox" class="pull-right" checked>
                </label>

                <p>
                Other sets of options are available
                </p>
              </div>
              <!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Expose author name in posts
                  <input type="checkbox" class="pull-right" checked>
                </label>

                <p>
                Allow the user to show his name in blog posts
                </p>
              </div>
              <!-- /.form-group -->

              <h3 class="control-sidebar-heading">Chat Settings</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Show me as online
                  <input type="checkbox" class="pull-right" checked>
                </label>
              </div>
              <!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Turn off notifications
                  <input type="checkbox" class="pull-right">
                </label>
              </div>
              <!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Delete chat history
                  <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                </label>
              </div>
              <!-- /.form-group -->
            </form>
          </div>
          <!-- /.tab-pane -->
        </div>
      </aside>
      <!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <%= yield :ext_scripts %>

  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head></head>
  <title>RailsWickedPdf
    <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
    <%= wicked_pdf_javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </title>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_breadcrumb.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Sidebar Collapsed
    <small>Layout with collapsed sidebar on load</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Layout</a></li>
    <li class="active">Collapsed Sidebar</li>
  </ol>
</section>

app/views/shared/_navbar_custom_menu.html.erb
<% if current_user %>
<div class="navbar-custom-menu">
  <ul class="nav navbar-nav">
    <li class="user user-menu">
      <%= link_to destroy_user_session_path, :method => :delete do %>
        <span class="hidden-xs">Logout</span>
      <% end %>
    </li>
    <!-- Control Sidebar Toggle Button -->
    <!--<li>
      <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
    </li>-->
  </ul>
</div> 
<% end %>

app/views/shared/_sidebar.html.erb
<% if current_user %>
<!-- =============================================== -->

<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p><%= current_user.email %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- search form -->
    <!--<form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    </form>-->
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <%= link_to dashboards_path do %>
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <% end %>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Master</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to aqmesh_data_path do %>
              <i class="fa fa-circle-o"></i> Aqmesh Data
            <% end %>
          </li> 
          <li>
            <%= link_to aqmesh_channels_path do %>
              <i class="fa fa-circle-o"></i> Aqmesh Channels
            <% end %>
          </li>
        </ul>
      </li>
      <!--<li class="treeview active">
        <a href="#">
          <i class="fa fa-files-o"></i>
          <span>Layout Options</span>
          <span class="pull-right-container">
            <span class="label label-primary pull-right">4</span>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
          <li><a href="boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
          <li><a href="fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
          <li class="active"><a href="collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a>
          </li>
        </ul>
      </li>-->            
      <!--<li class="treeview">
        <a href="#">
          <i class="fa fa-pie-chart"></i>
          <span>Charts</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
          <li><a href="../charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
          <li><a href="../charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
          <li><a href="../charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-laptop"></i>
          <span>UI Elements</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
          <li><a href="../UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
          <li><a href="../UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
          <li><a href="../UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
          <li><a href="../UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
          <li><a href="../UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-edit"></i> <span>Forms</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
          <li><a href="../forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
          <li><a href="../forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-table"></i> <span>Tables</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
          <li><a href="../tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
        </ul>
      </li>
      <li>
        <a href="../calendar.html">
          <i class="fa fa-calendar"></i> <span>Calendar</span>
          <span class="pull-right-container">
            <small class="label pull-right bg-red">3</small>
            <small class="label pull-right bg-blue">17</small>
          </span>
        </a>
      </li>
      <li>
        <a href="../mailbox/mailbox.html">
          <i class="fa fa-envelope"></i> <span>Mailbox</span>
          <span class="pull-right-container">
            <small class="label pull-right bg-yellow">12</small>
            <small class="label pull-right bg-green">16</small>
            <small class="label pull-right bg-red">5</small>
          </span>
        </a>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-folder"></i> <span>Examples</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
          <li><a href="../examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
          <li><a href="../examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
          <li><a href="../examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
          <li><a href="../examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
          <li><a href="../examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
          <li><a href="../examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
          <li><a href="../examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
          <li><a href="../examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-share"></i> <span>Multilevel</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          <li>
            <a href="#"><i class="fa fa-circle-o"></i> Level One
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
              <li>
                <a href="#"><i class="fa fa-circle-o"></i> Level Two
                  <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                  </span>
                </a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
        </ul>
      </li>
      <li><a href="../../documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
      <li class="header">LABELS</li>
      <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>-->
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

<!-- =============================================== -->
  
<% end %>