config/routes.rb
Rails.application.routes.draw do
  get 'latest/:station_number' => 'publicvars#latest'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'dashboards' => 'dashboards#index', as: :dashboards
  get  'dashboards/latest_chart_data' => 'dashboards#latest_chart_data'
  get  'dashboards/latest/:component' => 'dashboards#latest_chart_channel_component_data', as: :latest_chart_component_data
  get 'aqmesh_data/grab' => 'aqmesh_data#grab'
  get 'aqmesh_data/latest_timestamp/:n' => 'aqmesh_data#latest_timestamp'
  get 'aqmesh_channels/latest/:n/:label' => 'aqmesh_channels#latest_final'
  resources :aqmesh_channels
  resources :aqmesh_data
  get 'units/grab' => 'units#grab'
  get 'sensors/grab' => 'sensors#grab'
  resources :stations
  resources :servers
  resources :units
  resources :sensors

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  validates :name, uniqueness: true
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.page(params[:page])
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def grab
    items = getapi('sensors')
    @items = items
    @items.each do |e|
      name = e["Name"]
      label = e["Label"]
      Sensor.create!(name: name, label: label)
      p '==========================saved============================'
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :label)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.name %></td>
        <td><%= sensor.label %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @sensors %>
<br>
<%= link_to 'New Sensor', new_sensor_path, class: ['btn', 'btn-info'] %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sensor.name %>
</p>

<p>
  <strong>Label:</strong>
  <%= @sensor.label %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>