config/routes.rb
Rails.application.routes.draw do
  get 'latest/:station_number' => 'publicvars#latest'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'dashboards' => 'dashboards#index', as: :dashboards
  get  'dashboards/latest_chart_data' => 'dashboards#latest_chart_data'
  get  'dashboards/latest/:component' => 'dashboards#latest_chart_channel_component_data', as: :latest_chart_component_data
  get 'aqmesh_data/grab' => 'aqmesh_data#grab'
  get 'aqmesh_data/latest_timestamp/:n' => 'aqmesh_data#latest_timestamp'
  get 'aqmesh_channels/latest/:n/:label' => 'aqmesh_channels#latest_final'
  resources :aqmesh_channels
  resources :aqmesh_data
  get 'units/grab' => 'units#grab'
  get 'sensors/grab' => 'sensors#grab'
  resources :stations
  resources :servers
  resources :units
  resources :sensors

end

app/models/aqmesh_channel.rb
class AqmeshChannel < ActiveRecord::Base
  belongs_to :aqmesh_datum

  def self.latest_final_by_label(n,label)
    where("label = ?",label.upcase).last(n).map(&:final)  
  end

  def self.to_csv(col_sep)
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/aqmesh_channels_controller.rb
class AqmeshChannelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_aqmesh_channel, only: [:show, :edit, :update, :destroy]

  # GET /aqmesh_channels
  # GET /aqmesh_channels.json
  def index
    @aqmesh_channels = AqmeshChannel.page params[:page]
    @aqmesh_channels_order = AqmeshChannel.order(aqmesh_datum_id: :desc)
    respond_to do |format|
      format.html
      format.csv { send_data @aqmesh_channels_order.to_csv }
      format.xls { send_data @aqmesh_channels_order.to_csv(col_sep: "\t") }
    end

  end

  # GET /aqmesh_channels/1
  # GET /aqmesh_channels/1.json
  def show
  end

  # GET /aqmesh_channels/new
  def new
    @aqmesh_channel = AqmeshChannel.new
  end

  # GET /aqmesh_channels/1/edit
  def edit
  end

  # POST /aqmesh_channels
  # POST /aqmesh_channels.json
  def create
    @aqmesh_channel = AqmeshChannel.new(aqmesh_channel_params)

    respond_to do |format|
      if @aqmesh_channel.save
        format.html { redirect_to @aqmesh_channel, notice: 'Aqmesh channel was successfully created.' }
        format.json { render :show, status: :created, location: @aqmesh_channel }
      else
        format.html { render :new }
        format.json { render json: @aqmesh_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aqmesh_channels/1
  # PATCH/PUT /aqmesh_channels/1.json
  def update
    respond_to do |format|
      if @aqmesh_channel.update(aqmesh_channel_params)
        format.html { redirect_to @aqmesh_channel, notice: 'Aqmesh channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @aqmesh_channel }
      else
        format.html { render :edit }
        format.json { render json: @aqmesh_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aqmesh_channels/1
  # DELETE /aqmesh_channels/1.json
  def destroy
    @aqmesh_channel.destroy
    respond_to do |format|
      format.html { redirect_to aqmesh_channels_url, notice: 'Aqmesh channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def latest_final
    data = AqmeshChannel.latest_final_by_label(params[:n],params[:label]) 
    render json: data
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aqmesh_channel
      @aqmesh_channel = AqmeshChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aqmesh_channel_params
      params.require(:aqmesh_channel).permit(:aqmesh_datum_id, :pre_scaled, :scaled, :final, :offset, :slope, :status, :unit, :sensor, :label)
    end
end

app/helpers/aqmesh_channels_helper.rb
module AqmeshChannelsHelper
end

app/views/aqmesh_channels/_form.html.erb
<%= form_for(@aqmesh_channel) do |f| %>
  <% if @aqmesh_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aqmesh_channel.errors.count, "error") %> prohibited this aqmesh_channel from being saved:</h2>

      <ul>
      <% @aqmesh_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aqmesh_datum_id %><br>
    <%= f.text_field :aqmesh_datum_id %>
  </div>
  <div class="field">
    <%= f.label :pre_scaled %><br>
    <%= f.text_field :pre_scaled %>
  </div>
  <div class="field">
    <%= f.label :scaled %><br>
    <%= f.text_field :scaled %>
  </div>
  <div class="field">
    <%= f.label :final %><br>
    <%= f.text_field :final %>
  </div>
  <div class="field">
    <%= f.label :offset %><br>
    <%= f.text_field :offset %>
  </div>
  <div class="field">
    <%= f.label :slope %><br>
    <%= f.text_field :slope %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :sensor %><br>
    <%= f.text_field :sensor %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aqmesh_channels/edit.html.erb
<h1>Editing Aqmesh Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @aqmesh_channel %> |
<%= link_to 'Back', aqmesh_channels_path %>

app/views/aqmesh_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aqmesh Channels</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Aqmesh datum</th>
      <th>Pre scaled</th>
      <th>Scaled</th>
      <th>Final</th>
      <th>Offset</th>
      <th>Slope</th>
      <th>Status</th>
      <th>Unit</th>
      <th>Sensor</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aqmesh_channels.each do |aqmesh_channel| %>
      <tr>
        <td><%= aqmesh_channel.aqmesh_datum.timestamp %></td>
        <td><%= aqmesh_channel.pre_scaled %></td>
        <td><%= aqmesh_channel.scaled %></td>
        <td><%= aqmesh_channel.final %></td>
        <td><%= aqmesh_channel.offset %></td>
        <td><%= aqmesh_channel.slope %></td>
        <td><%= aqmesh_channel.status %></td>
        <td><%= aqmesh_channel.unit %></td>
        <td><%= aqmesh_channel.sensor %></td>
        <td><%= aqmesh_channel.label %></td>
        <td><%= link_to 'Show', aqmesh_channel %></td>
        <td><%= link_to 'Edit', edit_aqmesh_channel_path(aqmesh_channel) %></td>
        <td><%= link_to 'Destroy', aqmesh_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @aqmesh_channels %>
<br>
<%= link_to 'New Aqmesh channel', new_aqmesh_channel_path, class: %w{btn btn-primary} %>

app/views/aqmesh_channels/new.html.erb
<h1>New Aqmesh Channel</h1>

<%= render 'form' %>

<%= link_to 'Back', aqmesh_channels_path %>

app/views/aqmesh_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aqmesh datum:</strong>
  <%= @aqmesh_channel.aqmesh_datum %>
</p>

<p>
  <strong>Pre scaled:</strong>
  <%= @aqmesh_channel.pre_scaled %>
</p>

<p>
  <strong>Scaled:</strong>
  <%= @aqmesh_channel.scaled %>
</p>

<p>
  <strong>Final:</strong>
  <%= @aqmesh_channel.final %>
</p>

<p>
  <strong>Offset:</strong>
  <%= @aqmesh_channel.offset %>
</p>

<p>
  <strong>Slope:</strong>
  <%= @aqmesh_channel.slope %>
</p>

<p>
  <strong>Status:</strong>
  <%= @aqmesh_channel.status %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @aqmesh_channel.unit %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @aqmesh_channel.sensor %>
</p>

<p>
  <strong>Label:</strong>
  <%= @aqmesh_channel.label %>
</p>

<%= link_to 'Edit', edit_aqmesh_channel_path(@aqmesh_channel) %> |
<%= link_to 'Back', aqmesh_channels_path %>